apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: emailservice
spec:
  hosts:
  - emailservice.default.svc.cluster.local
  http:
  - fault:
      delay:
        fixedDelay: 20s
        percent: 100
    route:
    - destination:
        host: emailservice
  - route:
    - destination:
        host: emailservice
