apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shippingservice
spec:
  hosts:
  - shippingservice.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 50
    route:
    - destination:
        host: shippingservice
  - route:
    - destination:
        host: shippingservice
